#ifndef MEKO_CONFIG_PROCESSOR_H
#define MEKO_CONFIG_PROCESSOR_H

#if ENABLE_PARSER_TESTING_MODE == 1
#define PARSER_TESTING_MODE
#if PARSE_PRINT_PROGRESS_ONLY == 1
#define PARSER_ONLY_PROGRESS
#endif
#endif

#endif